# Generated by Django 4.0.3 on 2022-04-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteThisTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
