# Generated by Django 4.0.3 on 2022-04-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shapes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeleteThisTable',
        ),
    ]
